#########################
### Common parameters ###
#########################

exp: exp0
random_seed: 1

K: 3 # number previous timesteps to take in (i.e. 1 means only current)
H: 4 # number future timesteps to predict

##############################
### GP specific parameters ###
##############################

feature_type: 'position_velocity'
graph_type: 'fc' # fc /
kernel_size: 4

training_samples: 500 # number of training samples
std_max:

opt: adam # None / adam
learning_rate: 0.1 # only for opt adam
maxiter: 50
device: 1
gpu_fraction: 0.4

val_pct: 0.2
