#########################
### Common parameters ###
#########################

exp: exp0
random_seed: 1

K: 3 # number previous timesteps to take in (i.e. 1 means only current)
H: 3 # number future timesteps to predict

################################
### BDNN specific parameters ###
################################

bootstrap: 5
dropout:
samples: 1

feature_type: 'position_velocity_nearest'
features_per_file: 32

graph_type: 'fc_sub'
reg: 0.00001

device: 1
gpu_fraction: 0.4

val_pct: 0.2
batch_size: 64
learning_rate: 0.0001
max_step: 15000
val_step: 1000
display_step: 10
save_step: 1000
