#########################
### Common parameters ###
#########################

exp: exp1
random_seed: 1

K: 3 # number previous timesteps to take in (i.e. 1 means only current)
H: 6 # number future timesteps to predict

##############################
### GP specific parameters ###
##############################

feature_type: 'position_velocity'

training_samples: # number of training samples
std_max:

opt: # None / adam
learning_rate: 0.1 # only for opt adam
maxiter: 1000
device: 1
gpu_fraction: 0.4

val_pct: 0.2
