#########################
### Common parameters ###
#########################

exp: exp3
random_seed: 1

K: 3 # number previous timesteps to take in (i.e. 1 means only current)
H: 12 # number future timesteps to predict

#################################
### GP NN specific parameters ###
#################################

feature_type: 'position_velocity_nearest'
graph_type: 'fc' # fc /
kernel_size: 4

training_samples: 1000 # number of training samples
std_max:

opt: adam # None / adam
learning_rate: 0.01 # only for opt adam
maxiter: 2000
device: 1
gpu_fraction: 0.4

val_pct: 0.2

