#########################
### Common parameters ###
#########################

exp: exp99
random_seed: 1

K: 2 # number previous timesteps to take in (i.e. 1 means only current)
H: 3 # number future timesteps to predict

################################
### BDNN specific parameters ###
################################

bootstrap: 5
dropout:
samples: 1

feature_type: 'position'
features_per_file: 32

graph_type: 'fc'
reg: 0.001

device: 1
gpu_fraction: 0.4

val_pct: 0.2
batch_size: 2
learning_rate: 0.001
max_step: 10000
val_step: 1000
display_step: 10
save_step: 1000